Repository AY2324S2-CS2103T-F13-1/tp, pull requests merged in 2024-03, with the labels that each got.

#23 fix: image names to match format
  docs/AboutUs.md
  docs/images/anant1902.png
  docs/images/belligerentbeagle.png
  docs/images/foraeons.png
  docs/images/saiutkarsh33.png
  docs/images/tituschewxj.png
Labels: docs, priority.high

#25 Update User Guide to use TAPros keywords and phrases
  docs/UserGuide.md
Labels: docs, priority.medium

#18 Updated DG, UG, AboutUS
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: chore, docs

#29 Update Mark Command in UserGuide.md
  docs/UserGuide.md
Labels: docs

#30 Update name and contribution to xiaoyun.md
  .gitignore
  docs/team/xiaoyun.md
Labels: chore, priority.low

#39 chore: Add test coverage report to gitignore
  .gitignore
Labels: chore

#35 feat: Add message usage helper classes
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/FindPersonCommand.java
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/logic/commands/util/CommandMessageUsageUtil.java
  src/main/java/seedu/address/logic/commands/util/DefinedParameter.java
  src/main/java/seedu/address/logic/commands/util/Parameter.java
  src/main/java/seedu/address/logic/commands/util/ParameterSyntax.java
  src/test/java/seedu/address/logic/commands/util/CommandMessageUsageUtilTest.java
  src/test/java/seedu/address/logic/commands/util/DefinedParameterTest.java
  src/test/java/seedu/address/logic/commands/util/ParameterTest.java
Labels: feat

#21 feat: Mark attendance
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditPersonCommand.java
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ArgumentMultimap.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MarkAttendanceCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/model/weeknumber/WeekNumber.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedWeekNumber.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/Extensions.css
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
  src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
  src/test/java/seedu/address/logic/parser/MarkAttendanceCommandParserTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: feat, priority.high

#56 Delstu update DG
  docs/DeveloperGuide.md
Labels: docs

#24 feat: Change delete by index to delete by nusnet ID, and change command word to 'delstu'
  docs/UserGuide.md
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/DeletePersonCommand.java
  src/main/java/seedu/address/logic/parser/DeletePersonCommandParser.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java
Labels: feat, priority.high, type.story

#55 Reduce compulsory field for the addstu command
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddPersonCommand.java
  src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Phone.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/AddressTest.java
  src/test/java/seedu/address/model/person/EmailTest.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: priority.medium, type.student, type.class

#41 feat: Add commands in Help Window
  docs/UserGuide.md
  docs/images/helpMessage.png
  docs/images/helpWindow.png
  src/main/java/seedu/address/ui/HelpWindow.java
  src/main/java/seedu/address/ui/HelpWindowCommandCard.java
  src/main/resources/view/HelpWindow.css
  src/main/resources/view/HelpWindow.fxml
  src/main/resources/view/HelpWindowCommandCard.css
  src/main/resources/view/HelpWindowCommandCard.fxml
Labels: feat, priority.high, type.story

#60 feat: add trie data structure for autocomplete feature
  docs/DeveloperGuide.md
  src/main/java/seedu/address/commons/util/Trie.java
  src/main/java/seedu/address/commons/util/TrieNode.java
  src/test/java/seedu/address/commons/util/TrieNodeTest.java
  src/test/java/seedu/address/commons/util/TrieTest.java
Labels: feat, priority.low

#64 docs: update uml diagram to include NusNetId
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: docs, priority.high, type.uml

#65 docs: Update documentation links
  docs/DevOps.md
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/Testing.md
  docs/index.md
Labels: docs

#67 docs: Add UML diagrams for commands.util
  docs/diagrams/CommandsUtilClassDiagram.puml
  docs/diagrams/LogicClassDiagram.puml
Labels: docs, priority.high, type.uml

#53 Branch set course command
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/SetCourseCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/SetCourseCommandParser.java
  src/main/java/seedu/address/model/CourseName.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyCourseName.java
  src/main/java/seedu/address/model/ReadOnlyUserPrefs.java
  src/main/java/seedu/address/model/UserPrefs.java
  src/main/java/seedu/address/model/course/Course.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/CourseStorageName.java
  src/main/java/seedu/address/storage/JsonAdaptedCourse.java
  src/main/java/seedu/address/storage/JsonCourseNameStorage.java
  src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
  src/main/java/seedu/address/storage/JsonSerializableCourseName.java
  src/main/java/seedu/address/storage/Storage.java
  src/main/java/seedu/address/storage/StorageManager.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/UiManager.java
  src/test/java/seedu/address/commons/util/AppUtilTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ClearCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
  src/test/java/seedu/address/logic/commands/EditCommandTest.java
  src/test/java/seedu/address/logic/commands/FindCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
  src/test/java/seedu/address/logic/commands/MarkAttendanceCommandTest.java
  src/test/java/seedu/address/logic/commands/SetCourseCommandTest.java
  src/test/java/seedu/address/logic/commands/UnmarkAttendanceCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/logic/parser/SetCourseCommandParserTest.java
  src/test/java/seedu/address/model/CourseNameTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/UserPrefsTest.java
  src/test/java/seedu/address/model/util/SampleDataUtilTest.java
  src/test/java/seedu/address/storage/JsonAdaptedCourseTest.java
  src/test/java/seedu/address/storage/JsonCourseNameStorageTest.java
  src/test/java/seedu/address/storage/StorageManagerTest.java
  src/test/java/seedu/address/testutil/TypicalCourse.java
Labels: feat, priority.high, type.story

#66 chore: Update version number to v1.2
  src/main/java/seedu/address/MainApp.java
Labels: chore

#61 fix: CommandMessageUsageUtil missing prefix and extra spacing
  src/main/java/seedu/address/logic/commands/util/CommandMessageUsageUtil.java
  src/main/java/seedu/address/logic/commands/util/DefinedParameter.java
  src/main/java/seedu/address/logic/commands/util/Parameter.java
  src/test/java/seedu/address/logic/commands/util/CommandMessageUsageUtilTest.java
  src/test/java/seedu/address/logic/commands/util/DefinedParameterTest.java
Labels: priority.high, fix

#70 chore: Update archiveFileName
  build.gradle
Labels: chore

#73 docs: Update uml diagram to include WeekNumber
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: docs, priority.high, type.uml

#80 chore: Add MarkBind dev-dependency
  .gitignore
  docs/SettingUp.md
  package-lock.json
  package.json
Labels: chore

#81 chore: enable assertion in build.gradle file
  build.gradle
Labels: chore, priority.high

#79 fix: Fix markdown issue in DG
  docs/DeveloperGuide.md
Labels: docs, priority.high, fix

#62 feat: autocomplete command
  src/main/java/seedu/address/commons/util/Trie.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/autocomplete/AutoComplete.java
  src/main/java/seedu/address/logic/autocomplete/AutoCompleteCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/commons/util/TrieTest.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/autocomplete/AutoCompleteCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: feat, priority.medium, type.class

#84 Improve mark and unmark ::generatemessageusage
  src/main/java/seedu/address/logic/commands/MarkAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/UnmarkAttendanceCommand.java
  src/main/java/seedu/address/logic/commands/util/ParameterSyntax.java
Labels: chore

#71 feat: autocomplete nusnet id
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/autocomplete/AutoCompleteNusNetId.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/test/java/seedu/address/logic/autocomplete/AutoCompleteNusNetIdTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
Labels: feat, priority.medium, type.class

#95 Update DG
  docs/DeveloperGuide.md
Labels: docs

#92 Improve UI for attendance on PersonCard
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/PersonListCard.fxml
Labels: priority.medium, type.ui

#101 chore: Update version number for trial jar
  src/main/java/seedu/address/MainApp.java
Labels: chore, priority.high

#89 Use up-down arrows to navigate previous commands
  src/main/java/seedu/address/model/person/NusNet.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/CommandHistory.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/test/java/seedu/address/ui/CommandHistoryTest.java
Labels: feat, type.story

#98 feat: Improve result display UI
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/util/CommandMessageUsageUtil.java
  src/main/java/seedu/address/logic/commands/util/CommandWordUtil.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ResultDisplay.java
  src/main/java/seedu/address/ui/util/SyntaxHighlighter.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/ResultDisplay.fxml
  src/test/java/seedu/address/logic/commands/util/CommandMessageUsageUtilTest.java
  src/test/java/seedu/address/logic/commands/util/CommandWordUtilTest.java
  src/test/java/seedu/address/ui/util/SyntaxHighlighterTest.java
Labels: feat, type.ui

#108 Update DeveloperGuide.md
  docs/DeveloperGuide.md
Labels: docs, priority.medium

#120 fix: Incorrect window title from `setcrs`
  src/main/java/seedu/address/MainApp.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: priority.high, fix, type.ui, size.small

#121 feat: Move cursor to end after UP/DOWN
  src/main/java/seedu/address/ui/CommandBox.java
Labels: enhancement, priority.low, size.small
